pd/burials/urls.py
# coding: utf-8

from django.conf.urls import patterns, include, url
from django.conf import settings

#from django.views.generic import TemplateView # Django v1.5
from django.views.generic.simple import direct_to_template 

from users.models import Org


urlpatterns = patterns('burials.views',
    url(r'^$', 'dashboard', name='dashboard'),

    url(r'^burials/add_agent/$', 'add_agent', name='add_agent'),
    url(r'^burials/add_dover/$', 'add_dover', name='add_dover'),
    url(r'^burials/add_org/$', 'add_org', name='add_org'),
    url(r'^burials/add_zags/$', 'add_org', dict(type=Org.PROFILE_ZAGS), name='add_org'),
    url(r'^burials/add_doctype/$', 'add_doctype', name='add_doctype'),

    url(r'^burials/archive/$', 'archive', name='archive'),
    url(r'^burials/create/$', 'create_burial', name='create_burial'),
    url(r'^burials/get_place/$', 'get_place', name='get_place'),
    url(r'^burials/get_graves_number/$', 'get_graves_number', name='get_graves_number'),

    url(r'^burials/(?P<pk>\d+)/$', 'view_burial', name='view_burial'),
    url(r'^burials/(?P<pk>\d+)/edit/$', 'edit_burial', name='edit_burial'),
    url(r'^burials/(?P<pk>\d+)/notification/$', 'make_notification', name='make_notification'),
    url(r'^burials/(?P<pk>\d+)/spravka/$', 'make_spravka', name='make_spravka'),
    url(r'^burials/(?P<pk>\d+)/comment/$', 'burial_comment', name='burial_comment'),
    url(r'^burials/(?P<pk>\d+)/exhumate/$', 'burial_exhumate', name='burial_exhumate'),
    url(r'^burials/(?P<pk>\d+)/exhumate/cancel/$', 'burial_cancel_exhumation', name='burial_cancel_exhumation'),
    url(r'^burials/(?P<pk>\d+)/exhumate/report/$', 'make_exhumate_report', name='make_exhumate_report'),
    url(r'^burials/(?P<pk>\d+)/exhumate/notification/$', 'make_exhumate_notification', name='make_exhumate_notification'),
    url(r'^burials/$', 'burial_list', name='burial_list'),
    url(r'^burials/search/$', 'burial_public_list', name='burial_public_list'),
    
    url(r'^burialfiles/(?P<pk>\d+)/delete/$', 'delete_burialfile', name='delete_burialfile'),
    url(r'^burialfiles/(?P<pk>\d+)/editcomment/$', 'edit_burialfile_comment', name='edit_burialfile_comment'),

    url(r'^places/(?P<pk>\d+)/$', 'view_place', name='view_place'),
    url(r'^places/(?P<pk>\d+)/responsible/remove/$', 'rm_responsible', name='rm_responsible'),

    #url(r'^manage/cemetery/$', 'manage_cemeteries', name='manage_cemeteries'),
    #url(r'^manage/cemetery/create/$', 'manage_cemeteries_create', name='manage_cemeteries_create'),
    #url(r'^manage/cemetery/(?P<pk>\d+)/edit/$', 'manage_cemeteries_edit', name='manage_cemeteries_edit'),
    url(r'^manage/cemetery/(?P<pk>\d+)/merge/$', 'manage_cemeteries_merge', name='manage_cemeteries_merge'),

    url(r'^cemetery_times/', 'cemetery_times', name='cemetery_times'),
    url(r'^autocomplete/cemeteries/', 'autocomplete_cemeteries', name='autocomplete_cemeteries'),
    url(r'^autocomplete/areas/', 'autocomplete_areas', name='autocomplete_areas'),


    # REST API
    #url(r'^$', TemplateView.as_view(template_name='base_angular.html'),), # v1.5
    url(r'^manage/cemetery$', direct_to_template, {'template': 'base_angular.html'}, name='manage_cemeteries'),
)

pd/pd/urls.py
# coding: utf-8

from django.conf.urls import patterns, include, url
from django.views.generic.base import RedirectView
from django.conf import settings

#from django.views.generic import TemplateView # Django v1.5
from django.views.generic.simple import direct_to_template 
 

from django.contrib import admin
admin.autodiscover()

from rest_framework.routers import DefaultRouter
router = DefaultRouter(trailing_slash=False)



from geo.views import LocationViewSet, LocationStaticViewSet

from burials.views import CemeteryViewSet, AreaViewSet, PlaceViewSet, \
    GraveViewSet, BurialViewSet, AreaPhotoViewSet, GravePhotoViewSet, AreaPurposeViewSet, PlaceSizeViewSet

from persons.views import AlivePersonViewSet, DeadPersonViewSet, PhoneViewSet 
from logs.views import LogViewSet
 
from orders.views import CategoryViewSet, ProductViewSet 
 
# Burial
router.register(r'^api/catalog/category', CategoryViewSet)
router.register(r'^api/catalog/product', ProductViewSet)

router.register(r'^api/log', LogViewSet)
router.register(r'^api/cemetery', CemeteryViewSet)
router.register(r'^api/area', AreaViewSet)
router.register(r'^api/place', PlaceViewSet)

router.register(r'^api/place', PlaceViewSet)
router.register(r'^api/grave', GraveViewSet)
router.register(r'^api/burial', BurialViewSet)
router.register(r'^api/grave-photo', GravePhotoViewSet)
router.register(r'^api/area-photo', AreaPhotoViewSet)
router.register(r'^api/area-purpose', AreaPurposeViewSet)

router.register(r'^api/alive-person', AlivePersonViewSet)
router.register(r'^api/dead-person', DeadPersonViewSet)

router.register(r'^api/alive-person-phone', PhoneViewSet)
router.register(r'^api/placesize', PlaceSizeViewSet)



# Geo
router.register(r'^api/geo/location', LocationViewSet)
router.register(r'^api/geo/location/static', LocationStaticViewSet)

urlpatterns = patterns('',
    url(r'^thumb/', include('restthumbnails.urls')),
)

urlpatterns += patterns('pd.views',
    url(r'^favicon\.ico$',
        RedirectView.as_view(url='{0}img/favicon16x16.ico'.format(settings.STATIC_URL))),
    url(r'^', include('users.urls')),
    url(r'^', include('burials.urls')),
    url(r'^', include('persons.urls')),
    url(r'^', include('orders.urls')),
    url(r'^', include('reports.urls')),
    url(r'^', include('mobile.urls')),
    url(r'^geo/', include('geo.urls')),
    url(r'^import/', include('import_burials.urls')),
    
    url(r'^api/', include('rest_api.urls')),
    url(r'^', include(router.urls)),
)

# Redirects. Move into nginx at production
urlpatterns += patterns('rest_api.views',
    url(r'^api$', 'api_root'),
    url(r'^manage/404$', 'base_page'),
    url(r'^manage/500$', 'base_page'),
    url(r'^manage/cemetery/$', 'base_page'),
    url(r'^manage/cemetery/(?P<id>.*)$', 'base_page'),
    url(r'^manage/area/(?P<id>.*)$', 'base_page'),
    url(r'^manage/place/(?P<id>.*)$', 'base_page'),
)

# Для включения административных функций (http://.../admin)
# добавить параметр ADMIN_ENABLED  в pd/local_settings.py (!)
# и установить его в True
#
if 'ADMIN_ENABLED' in dir(settings) and settings.ADMIN_ENABLED:
    urlpatterns += patterns('',
        url(r'^admin/jsi18n/', 'django.views.i18n.javascript_catalog'),
        url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
        url(r'^admin/', include(admin.site.urls)),
    )

urlpatterns += patterns('',
    #
    # url(r'^media/(?P<path>.*)$',  'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    #
    # Здесь django.views.static.serve заменена на свою функцию
    # pd.views.media_xsendfile, которая проверяет, работаем ли мы под сервером Apache и если да,
    # то проверяем доступ к media файлу. Если проверки успешны, то Apache с mod_xsendfile
    # передает media файл клиенту.
    # Если работаем не под сервером Apache, а пока это только из ./manage.py runserver, то 
    # управление передается на django.views.static.serve, но это без проверок доступа к файлу
    #
    url(r'^media/(?P<path>.*)$',  'pd.views.media_xsendfile', {'document_root': settings.MEDIA_ROOT}),
)

if settings.DEBUG:
    urlpatterns += patterns('',
            url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    )

pd/burials/models.py
# coding=utf-8
import datetime
import re
from django.contrib.contenttypes.models import ContentType
from django.db import models, connection
from django.db.models import Count, Avg
from django.db.models.deletion import ProtectedError
from django.utils.translation import ugettext_lazy as _
from django.db.models.query_utils import Q
from django.conf import settings
from pd.models import UnclearDateModelField, BaseModel, Files, GetLogsMixin, validate_gt0

from persons.models import DeadPerson, SafeDeleteMixin, DeathCertificate, PhonesMixin
from reports.models import Report
from users.models import Org, Profile, Dover, ProfileLORU
from logs.models import Log
from geo.models import GeoPointModel

from geo.models import GeoPointModel


class Cemetery(GetLogsMixin, BaseModel, PhonesMixin):
    PLACE_AREA = 'area'
    PLACE_ROW = 'row'
    PLACE_CEM_YEAR = 'cem_year'
    PLACE_BURIAL_ACCOUNT_NUMBER = 'burial_account_number'
    PLACE_MANUAL = 'manual'
    PLACE_TYPES = (
        (PLACE_AREA, _(u'По участку')),
        (PLACE_ROW, _(u'По ряду')),
        (PLACE_CEM_YEAR, _(u'Кладбище + год')),
        (PLACE_BURIAL_ACCOUNT_NUMBER, _(u'По рег. номеру захоронения')),
        (PLACE_MANUAL, _(u'Вручную')),
    )

    PLACE_ARCHIVE_MANUAL = 'manual'
    PLACE_ARCHIVE_PREFIX_AREA = '-area'
    PLACE_ARCHIVE_BURIAL_ACCOUNT_NUMBER = 'burial_account_number'
    PLACE_ARCHIVE_TYPES = (
        (PLACE_ARCHIVE_MANUAL, _(u'Вручную')),
        (PLACE_ARCHIVE_PREFIX_AREA, _(u'По порядку в пределах участка (-0001 -0002...)')),
        (PLACE_ARCHIVE_BURIAL_ACCOUNT_NUMBER, _(u'По рег. номеру захоронения')),
    )

    name = models.CharField(_(u"Название"), max_length=255)
    time_begin = models.TimeField(_(u"Начало работы"), null=True, blank=True)
    time_end = models.TimeField(_(u"Окончание работы"), null=True, blank=True)
    places_algo = models.CharField(_(u"Расстановка номеров мест захоронений (кроме архивных)"),
                                max_length=255, choices=PLACE_TYPES, default=PLACE_AREA)
    places_algo_archive = models.CharField(_(u"Расстановка номеров мест архивных захоронений"),
                                max_length=255, choices=PLACE_ARCHIVE_TYPES, default=PLACE_ARCHIVE_MANUAL)
    time_slots = models.TextField(_(u"Время для захоронения"), default='', blank=True,
                                  help_text=_(u'В формате ЧЧ:ММ, по одному на строку'))

    creator = models.ForeignKey('auth.User', verbose_name=_(u"Владелец"),
                                on_delete=models.PROTECT)
    ugh = models.ForeignKey(Org, verbose_name=_(u"УГХ"), null=True, limit_choices_to={'type': Org.PROFILE_UGH},
                            on_delete=models.PROTECT)
    address = models.ForeignKey('geo.Location', editable=False, null=True)
    archive_burial_fact_date_required = models.BooleanField(_(u"Дата архивного захоронения обязательна"), default=True)
    archive_burial_account_number_required = models.BooleanField(_(u"Номер архивного захоронения обязателен"), default=True)

    class Meta:
        verbose_name = _(u"Кладбище")
        verbose_name_plural = _(u"Кладбища")
        ordering = ['name']
        unique_together = ('ugh', 'name',)

    def __unicode__(self):
        return self.name

    def get_time_choices(self, date, request):
        others = Burial.objects.none()
        others_loru = Burial.objects.none()
        if date:
            others = Burial.objects.filter(cemetery=self, plan_date=date)
            others_loru = Burial.objects.filter(applicant_organization=request.user.profile.org, plan_date=date)
        result = []

        for s in self.time_slots.split('\n'):
            if s.strip():
                planned = filter(lambda b: b.is_ready() and b.plan_time.strftime('%H:%M') == s, others)
                approved = filter(lambda b: b.is_approved() and b.plan_time.strftime('%H:%M') == s, others)
                if request.user.profile.is_loru():
                    planned_others = filter(lambda b: b.is_ready() and b.plan_time.strftime('%H:%M') == s, others_loru)
                    approved_others = filter(lambda b: b.is_approved() and b.plan_time.strftime('%H:%M') == s, others_loru)
                    v = u'%s (резерв кладб. %s, лору%s)' % (s, len(planned)+len(approved), len(planned_others)+len(approved_others))
                else:
                    v = u'%s (резерв кладб. %s)' % (s, len(planned)+len(approved))
                result.append((s, v))
        return result
    
    @property
    def area_cnt(self):
        # TODO: replace with field, updated trought signals 
        return self.area_set.count()

    @property
    def work_time(self):
        return "%s-%s" % (self.time_begin or u'00:00:00', self.time_end or u'00:00:00')



class AreaPurpose(models.Model):
    name = models.CharField(_(u"Название"), max_length=255)

    class Meta:
        verbose_name = _(u"Назначение участков")
        verbose_name_plural = _(u"Назначение участков")

    def __unicode__(self):
        return self.name


class Area(BaseModel):
    AVAILABILITY_OPEN = 'open'
    AVAILABILITY_OLD = 'old_only'
    AVAILABILITY_CLOSED = 'closed'

    AVAILABILITY_CHOICES = (
        (AVAILABILITY_OPEN, _(u'Открыт')),
        (AVAILABILITY_OLD, _(u'Только подзахоронения')),
        (AVAILABILITY_CLOSED, _(u'Закрыт')),
    )

    cemetery = models.ForeignKey(Cemetery, verbose_name=_(u"Кладбище"), on_delete=models.PROTECT)
    name = models.CharField(_(u"Название"), max_length=255)
    availability = models.CharField(_(u"Открытость"), max_length=32, choices=AVAILABILITY_CHOICES, null=True)
    purpose = models.ForeignKey(AreaPurpose, verbose_name=_(u"Назначение"), null=True, on_delete=models.PROTECT)
    places_count = models.PositiveIntegerField(_(u"Макс. кол-во могил в месте"), default=1)

    class Meta:
        verbose_name = _(u"Участок")
        verbose_name_plural = _(u"Участки")
        ordering = ['name']
        unique_together = ('cemetery', 'name',)

    def __unicode__(self):
        return _(u'%s (%s, %s, %s могил)') % (
            self.name,
            self.get_availability_display() or _(u"откр.неизв"), self.purpose or _(u"назн. неизв"),
            self.places_count
        )

    def save(self, *args, **kwargs):
        if not self.name.strip():
            self.name=''
        return super(Area, self).save(*args, **kwargs)

class Place(SafeDeleteMixin, GeoPointModel):
    cemetery = models.ForeignKey(Cemetery, verbose_name=_(u"Кладбище"), on_delete=models.PROTECT)
    area = models.ForeignKey(Area, verbose_name=_(u"Участок"), blank=True, null=True,
                             on_delete=models.PROTECT)
    row = models.CharField(_(u"Ряд"), max_length=255, blank=True, null=True)
    oldplace = models.CharField(_(u"Старое место"), max_length=255, blank=True, null=True)
    place = models.CharField(_(u"Место"), max_length=255, blank=True, null=True)
    available_count = models.PositiveSmallIntegerField(_(u"Число свободных мест"), default=0)
    responsible = models.ForeignKey('persons.AlivePerson', verbose_name=_(u"Ответственный"), blank=True, null=True,
                                    on_delete=models.PROTECT)
    place_length = models.DecimalField(_(u"Длина, м."), max_digits=5, decimal_places=2,
                                       null=True, blank=True, validators=[validate_gt0])
    place_width = models.DecimalField(_(u"Ширина, м."), max_digits=5, decimal_places=2,
                                        null=True, blank=True, validators=[validate_gt0])
    
    class Meta:
        verbose_name = _(u"Место")
        verbose_name_plural = _(u"Место")
        unique_together = ('cemetery', 'area', 'row', 'place',)
        ordering = ['row', 'place']

    def __unicode__(self):
        return _(u'Кл. %s, уч. %s, ряд %s, место %s') % (self.cemetery, self.area and self.area.name or '', self.row, self.place)

    def burials_available(self):
        q_ex = Q(status=Burial.STATUS_EXHUMATED) | Q(annulated=True)
        return self.burial_set.exclude(q_ex)

    def burial_count(self):
        return self.burials_available().distinct('grave').count()

    def get_graves_count(self):
        return self.grave_set.count()

    def get_available_count(self):
        """
        Deprecated func
        please use 'self.available_count' which is updated via signals
        """
        return self.available_count
        #return max(0, self.get_graves_count() - self.burial_count())

    def set_next_number(self, new_place_for_archive=False):
        if new_place_for_archive:
            assert self.cemetery and \
                self.cemetery.places_algo_archive in (Cemetery.PLACE_ARCHIVE_PREFIX_AREA, ), \
                u'Empty place number for a new archive burial and no appropriate algorythm'
        elif self.cemetery.places_algo in (Cemetery.PLACE_MANUAL,
                                           Cemetery.PLACE_BURIAL_ACCOUNT_NUMBER,
                                          ):
            return

        filter = 'cemetery_id=%s' % (self.cemetery.pk, )
        if new_place_for_archive:
            # self.cemetery.places_algo_archive == Cemetery.PLACE_ARCHIVE_PREFIX_AREA:
            # пока это едиственный выбор для заполнения пустого места архивного зх
            prefix = '-'
            num_template = '%05d'
            filter += ' and area_id=%s' % (self.area.pk, )
        else:
            prefix = ''
            num_template = '%d'
            if self.cemetery.places_algo == Cemetery.PLACE_ROW:
                filter += " and area_id=%s and row='%s'" % (self.area.pk, self.row, )
            elif self.cemetery.places_algo == Cemetery.PLACE_AREA:
                filter += ' and area_id=%s' % (self.area.pk, )
            elif self.cemetery.places_algo == Cemetery.PLACE_CEM_YEAR:
                prefix = str(datetime.datetime.now().year)
                num_template = '%04d'
            else:
                return

        p_regex = r"E'^%s\\d+$'" % (re.escape(prefix), )

pd/templates/applicant_form.html
{% load i18n %}

<h2>
    {% if 'order' in request.path %}
        {% trans "Заказчик" %}
    {% else %}
        {% trans "Заявитель" %}
    {% endif %}
    {% if form.instance.applicant_organization %}
        {{ form.instance.applicant_organization }}
    {% elif form.instance.applicant %}
        {{ form.instance.applicant }}
    {% else %}
    {% endif %}
</h2>
<div id="cont_applicant">
    {{ form.opf.errors }}
    <p>{{ form.opf.label_tag }} {{ form.opf }}<span class="helptext">{{ form.opf.help_text }}</span></p>

    <div id="applicant_form_org">
        {{ form.applicant_organization.errors }}
        <div class="inline">
            {{ form.applicant_organization.label_tag }} {{ form.applicant_organization }}<span class="helptext">{{ form.applicant_organization.help_text }}</span>
            <p class="inline">
                <a href="#add_loru" role="button" class="btn btn-loru" data-toggle="modal">
                    {% trans "добавить юрлицо" %}
                </a>
                <a href="#" class="btn btn-edit-org" target="_blank">
                    {% trans "править" %}
                </a>
                <div id="cannot_edit_org_message" class="inline" style="padding-left: 10px; vertical-align: top;">
                    {% trans "Правка организации с активными пользователями недоступна." %}<br />
                    {% include "goto_support.html" %}
                </div>
            </p>
            <script type="text/javascript">
                ORGS_INACTIVE = [{% for org in form.fields.applicant_organization.inactive_queryset %}"{{ org.pk }}"{% if not forloop.last %},{% endif %}{% endfor %}];
                ORGS_LIST = [{% for org in form.fields.applicant_organization.queryset %}"{{ org.name|escapejs }}"{% if not forloop.last %},{% endif %}{% endfor %}];
                $(function() {
                    $('select[name$=applicant_organization]').attr('autocomplete', 'off').change(function() {
                        if (ORGS_INACTIVE.indexOf($(this).val()) > -1) {
                            $('.btn-edit-org').attr('href', '/org/'+$(this).val()+'/edit/').show();
                            $('#cannot_edit_org_message').hide();
                        } else {
                            $('.btn-edit-org').hide();
                            if ($(this).val()) {
                                $('#cannot_edit_org_message').show();
                            } else {
                                $('#cannot_edit_org_message').hide();
                            }
                        }
                    }).each(function() {
                        var sel_input = $(this);
                        var ac_input = $('<input type="text">');
                        if (sel_input.find('option:selected').attr('value')) {
                            ac_input.val(sel_input.find('option:selected').text());
                        }
                        ac_input.insertAfter(sel_input);
                        sel_input.hide();
                        ac_input.typeahead({
                            items: 100,
                            source: ORGS_LIST,
                            onselect: function() {
                                ac_input.change();
                            },
                            highlighter : function(item){
                                return item.replace(new RegExp('(' + escapeRegExp(this.query) + ')', 'ig'), function ($1, match) {
                                    return '<strong>' + match + '</strong>'
                                })
                            }
                        }).change(function() {
                            var item = $(this).val();
                            var processed = false;
                            sel_input.find('option').each(function() {
                                if ($(this).text() == item) {
                                    sel_input.val($(this).attr('value'));
                                    sel_input.change();
                                    processed = true;
                                }
                            });
                            if (!processed) {
                                alert("Указана несуществующая организация");
                                ac_input.val(sel_input.find('option:selected').text());
                            }
                        });
                    });
                    $('input[name$=applicant_organization]').change();
                    $("#cont_applicant ul").each(function(index,element){
                        $(this).addClass("unstyled");
                    });
                    $("form.order_form ul").each(function(index,element){
                        $(this).addClass("unstyled");
                    });

                });
            </script>
        </div>

        <h2>{% trans "Агент" %}</h2>

        {{ form.agent_director.errors }}
        <p>{{ form.agent_director.label_tag }} {{ form.agent_director }}<span class="helptext">{{ form.agent_director.help_text }}</span></p>

        {{ form.agent.errors }}
        <div class="inline">
            {{ form.agent.label_tag }} {{ form.agent }}<span class="helptext">{{ form.agent.help_text }}</span>
            <p>
                <a href="#add_agent" role="button" class="btn btn-agent" data-toggle="modal">
                    {% trans "добавить агента" %}
                </a>
            </p>
        </div>

        {{ form.dover.errors }}
        <div class="inline">
            {{ form.dover.label_tag }} {{ form.dover }}<span class="helptext">{{ form.dover.help_text }}</span>
            <p>
                <a href="#add_dover" role="button" class="btn btn-dover" data-toggle="modal">
                    {% trans "добавить доверенность" %}
                </a>
            </p>
        </div>
        <br/>
    </div>

    <div id="applicant_form_person">
        {{ form.applicant_form.as_p }}
        <h3>{% trans "Адрес" %}</h3>
        <div class="form_block">
            {% with form.applicant_address_form as form %}
                {% include "location_form.html" %}
            {% endwith %}
        </div>
        <h3>{% trans "Удостоверение личности" %}</h3>
        <div class="form_block">
            {{ form.applicant_id_form.id_type.errors }}
            {% if 'burial' in request.path and not request.REQUEST.archive and not form.instance.is_archive %}    
                <p>
                    {{ form.applicant_id_form.flag_no_applicant_doc_required.label_tag }} {{ form.applicant_id_form.flag_no_applicant_doc_required }}
                    <span class="helptext">{{ form.applicant_id_form.flag_no_applicant_doc_required.help_text }}</span>
                </p>
            {% endif %}    
            <p class="inline">
                {{ form.applicant_id_form.id_type.label_tag }} {{ form.applicant_id_form.id_type }}
                <span class="helptext">{{ form.applicant_id_form.id_type.help_text }}</span>
            </p>
            <p class="inline">
                <a href="#add_doctype" role="button" class="btn" data-toggle="modal">
                    {% trans "добавить тип" %}
                </a>
            </p>

            {{ form.applicant_id_form.series.errors }}
            <p class="inline">
                {{ form.applicant_id_form.series.label_tag }} {{ form.applicant_id_form.series }}
                <span class="helptext">{{ form.applicant_id_form.series.help_text }}</span>
            </p>

            {{ form.applicant_id_form.number.errors }}
            <p class="inline">
                {{ form.applicant_id_form.number.label_tag }} {{ form.applicant_id_form.number }}
                <span class="helptext">{{ form.applicant_id_form.number.help_text }}</span>
            </p>

            {{ form.applicant_id_form.source.errors }}
            <p class="inline">
                {{ form.applicant_id_form.source.label_tag }} {{ form.applicant_id_form.source }}
                <span class="helptext">{{ form.applicant_id_form.source.help_text }}</span>
            </p>

            {{ form.applicant_id_form.date.errors }}
            <p class="inline">
                {{ form.applicant_id_form.date.label_tag }} {{ form.applicant_id_form.date }}
                <span class="helptext">{{ form.applicant_id_form.date.help_text }}</span>
            </p>
        </div>
    </div>
</div>

pd/templates/edit_burialfile_comment.html
{% extends "base.html" %}

{% load i18n %}

{% block content %}
    <h3>{% trans "Редактировать описание" %}</h3>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <p>
            <input type="submit" class="btn" value="{% trans "cохранить" %}"/>
        </p>
    </form>
{% endblock %}

pd/templates/exhumate_burial.html
{% extends "base.html" %}

{% load i18n %}

{% block content %}
    <h1>{% trans "Эксгумация" %}</h1>
    {{ form.non_field_errors }}
    <dl>
        <dt>{% trans "Захоронение" %}</dt>
        <dd>{{ burial }}</dd>
        <dt>{% trans "Место" %}</dt>
        <dd>{{ burial.get_place }}</dd>
    </dl>
    <form action="{{ request.path }}" method="POST" class="burial-form">
        {% csrf_token %}
        <input id="id_cemetery" value="{{ burial.cemetery.pk }}" type="hidden" />

        {% if form.fact_date %}
            {{ form.fact_date.errors }}
            <p class="inline">{{ form.fact_date.label_tag }} {{ form.fact_date }}<span class="helptext">{{ form.fact_date.help_text }}</span></p>
        {% endif %}

        {% if form.plan_date %}
            {{ form.plan_date.errors }}
            <p class="inline">{{ form.plan_date.label_tag }} {{ form.plan_date }}<span class="helptext">{{ form.plan_date.help_text }}</span></p>
        {% endif %}

        {% if form.plan_time %}
            {{ form.plan_time.errors }}
            <p class="inline">{{ form.plan_time.label_tag }} {{ form.plan_time }}<span class="helptext">{{ form.plan_time.help_text }}</span></p>
        {% endif %}

        {% include "applicant_form.html" %}

        {% block buttons %}
            <p class="clear">
                <input type="submit" class="btn btn-primary btn-commit-burial" value="{% trans "сохранить" %}"/>
            </p>
        {% endblock buttons %}
    </form>

    {% include "create_burial_popups.html" %}

    <script type="text/javascript">
        AGENT_DOVER = {{ form.agent_dover_json|default:"{}"}};
        ORG_AGENTS = {{ form.loru_agents_json|default:"{}"}};
        ACTUAL_DOVER = [{% for d in form.actual_dover_list %}{{ d }}{% if not forloop.last %},{% endif %}{% endfor %}];
    </script>
{% endblock %}